spring:
  application.name: SVLCF
  profiles.active: local
  datasource:
    username: root
    password: svlcfdb
  jpa:
    open-in-view: false
    hibernate.ddl-auto: update
server:
  port: 9001
  servlet.context-path: /svlcf
  tomcat.threads.max: 1
logging:
  level:
    root: INFO
    org:
      springframework.web.servlet.DispatcherServlet: DEBUG
      apache.pdfbox.pdmodel.font.PDType1Font: ERROR
  file.max-size: 50MB
management.endpoints.web.exposure.include: metrics

---
spring:
  config.activate.on-profile: docker
  datasource.url: jdbc:mysql://svlcfmysql:3306/svlcfdb
logging.file.name: home/Data/Logs/logFile.log
svlcf.config.pdfOutputRootPath: home/Data/

---
spring:
  config.activate.on-profile: local
  datasource.url: jdbc:mysql://localhost:3306/svlcfdb
logging.file.name: C:\Data\OneDrive\Logs\logFile.log
svlcf.config.pdfOutputRootPath: C:/Data/OneDrive/